// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcIplApp.Data;

#nullable disable

namespace MvcIplApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MvcIplApp.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Captain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Coach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Captain = "Ruturaj Gaikwad",
                            Coach = "Stephen Fleming",
                            FullName = "Chennai Super Kings",
                            Title = "CSK",
                            Venue = "M. A. Chidambaram Stadium"
                        },
                        new
                        {
                            Id = 2,
                            Captain = "Rishabh Pant",
                            Coach = "Ricky Ponting",
                            FullName = "Delhi Capitals",
                            Title = "DC",
                            Venue = "Arun Jaitley Stadium"
                        },
                        new
                        {
                            Id = 3,
                            Captain = "Faf du Plessis",
                            Coach = "Sanjay Bangar",
                            FullName = "Royal Challengers Bengaluru",
                            Title = "RCB",
                            Venue = "M. Chinnaswamy Stadium"
                        },
                        new
                        {
                            Id = 4,
                            Captain = "Shubman Gill",
                            Coach = "Ashish Nehra",
                            FullName = "Gujarat Titans",
                            Title = "GT",
                            Venue = "Narendra Modi Stadium"
                        },
                        new
                        {
                            Id = 5,
                            Captain = "Shreyas Iyer",
                            Coach = "Chandrakant Pandit",
                            FullName = "Kolkata Knight Riders",
                            Title = "KKR",
                            Venue = "Eden Gardens"
                        },
                        new
                        {
                            Id = 6,
                            Captain = "KL Rahul",
                            Coach = "Justin Langer",
                            FullName = "Lucknow Super Giants",
                            Title = "LSG",
                            Venue = "BRSABV Ekana Cricket Stadium"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
