CREATE TABLE EMPLOYEE(EMPID INT,EMPNAME VARCHAR(100),EMPSALARY INT,EMPDEPTID INT);

INSERT INTO EMPLOYEE VALUES(1,'ANAND',70000,1);
insert into employee values(2,'RAJ',2000,5);
INSERT INTO EMPLOYEE VALUES(3,'ABHISHEK',70000,6);
INSERT INTO EMPLOYEE VALUES(1,'AYUSH',60000,2);
INSERT INTO EMPLOYEE VALUES(3,'MUKUD',21500,3);
INSERT INTO EMPLOYEE VALUES(4,'VENU',80000,2);
INSERT INTO EMPLOYEE VALUES(5,'Adi',35000,4);
insert into EMPLOYEE values(8, 'Aditya', 50000, 6);
INSERT INTO EMPLOYEE VALUES(9,'Spardha',21545,7);
INSERT INTO EMPLOYEE values(8,'Subhendu',70000,1);

SELECT * FROM EMPLOYEE

CREATE TABLE DEPT(DEPTID INT,DEPTNAME VARCHAR(100));

INSERT INTO DEPT VALUES(1,'MICROSOFT');
INSERT INTO DEPT VALUES(2,'SAP');
insert into dept values(4,'Data Analytics');
INSERT INTO DEPT VALUES(3,'SALESFORCE');

SELECT * FROM DEPT



select * from employee
where EmpSalary BETWEEN 30000 AND 70000

select * from employee WHERE EmpName like '%a'

select * from employee WHERE EmpName not like '%a%'

select * from employee WHERE EmpId IN (1,3,5,7)

