//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_project.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Emp_ID { get; set; }
        public string Emp_Name { get; set; }
        public string Job { get; set; }
        public int Salary { get; set; }
    }
}
