using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using static System.Windows.Forms.AxHost;
using static System.Windows.Forms.VisualStyles.VisualStyleElement;
using static System.Windows.Forms.VisualStyles.VisualStyleElement.ToolTip;

namespace QuizGame
{
    public partial class Form1 : Form
    {
        int correctAnswer;
        int questionNumber = 1;
        int score;
        int percentage;
        int totalQuestions;



        public Form1()
        {
            InitializeComponent();
            askQuestions(questionNumber);
            totalQuestions = 6;
        }

        private void CheckAnswerEvent(object sender, EventArgs e)
        {
            var senderObject = (System.Windows.Forms.Button)sender;
            int buttonTag = Convert.ToInt32(senderObject.Tag);
            if (buttonTag == correctAnswer) 
            {
                score++;
            }
            if (questionNumber == totalQuestions)
            {

                percentage = (int)Math.Round((double)(score * 100) / totalQuestions);


                MessageBox.Show(
                    "The quiz has ended." + Environment.NewLine + "You were able to answer " +
                    score + " questions correctly." + Environment.NewLine + "Your total percentage is "
                    + Environment.NewLine + percentage + "%" + Environment.NewLine
                    + "Click OK to play again!");
                score = 0;
                questionNumber = 0;
                askQuestions(questionNumber);
            }

            questionNumber++;
            askQuestions(questionNumber);

        }
        private void askQuestions(int qnum)
        {
            switch (qnum)
            {
                case 1:
                    pictureBox1.Image = Properties.Resources.R;
                    QuestionBox.Text = "Who is the current Prime Minister of England?";
                    button1.Text = "Hillary Clinton";
                    button12.Text = "Rishi Sunak";
                    button13.Text = "Boris Johnson";
                    button4.Text = "Dominic Raab";
                    correctAnswer = 2;
                    break;

                case 2:
                    pictureBox1.Image = Properties.Resources.Source_newsweek_1024x668;
                    QuestionBox.Text = "The central banking functions in India are performed by the";
                    button1.Text = "Central Bank of India";
                    button12.Text = "Reserve Bank of India";
                    button13.Text = " State Bank of India";
                    button4.Text = "Punjab National Bank";
                    correctAnswer = 2;
                    break;

                case 3:
                    pictureBox1.Image = Properties.Resources.Tsunami_Essay;
                    QuestionBox.Text = " A tsunami is a series of giant waves generated by";
                    button1.Text = "High winds";
                    button12.Text = "Stronger than normal tides";
                    button13.Text = "Large disturbance on the ocean floor ";
                    button4.Text = "Storms";
                    correctAnswer = 3;
                    break;

                case 4:
                    pictureBox1.Image = Properties.Resources._1200px_Costa_Rican_Dance_Performance;
                    QuestionBox.Text = " Which of the following is not a river in Cuba?";
                    button1.Text = "Cauto";
                    button12.Text = "Zaza";
                    button13.Text = "Sagua la Grande ";
                    button4.Text = "Rio Grande";
                    correctAnswer = 4;
                    break;

                case 5:
                    pictureBox1.Image = Properties.Resources.OIP;
                    QuestionBox.Text = "In Australia, the average annual cost of floods is around";
                    button1.Text = "$3.8 million";
                    button12.Text = "$38 million";
                    button13.Text = "$380 million ";
                    button4.Text = "$3.8 billion";
                    correctAnswer = 3;
                    break;

                case 6:
                    pictureBox1.Image = Properties.Resources.download;
                    QuestionBox.Text = "Which actress has the lead role in “The Princess Switch”?";
                    button1.Text = "Vanessa Hudgens";
                    button12.Text = "Emily Blunt";
                    button13.Text = " Zendaya";
                    button4.Text = "Sydney Sweeney";
                    correctAnswer = 1;
                    break;
                }
            }
    }
}

