//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework.ConsumerTable
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyconsumersEntities : DbContext
    {
        public MyconsumersEntities()
            : base("name=MyconsumersEntities")
        {
        }
   
    
        public virtual DbSet<ConsTable> ConsTables { get; set; }
    }
}
