USE [master]
GO

/****** Object:  Database [MusicDb]    Script Date: 28-03-2024 18:24:46 ******/
CREATE DATABASE [MusicDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MusicDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\MusicDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MusicDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\MusicDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MusicDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MusicDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MusicDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MusicDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MusicDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MusicDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [MusicDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MusicDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MusicDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MusicDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MusicDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MusicDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MusicDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MusicDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MusicDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MusicDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MusicDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MusicDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MusicDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MusicDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MusicDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MusicDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MusicDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MusicDb] SET RECOVERY FULL 
GO

ALTER DATABASE [MusicDb] SET  MULTI_USER 
GO

ALTER DATABASE [MusicDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MusicDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MusicDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MusicDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MusicDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MusicDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [MusicDb] SET QUERY_STORE = ON
GO

ALTER DATABASE [MusicDb] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [MusicDb] SET  READ_WRITE 
GO


