--SQL JOINs

CREATE TABLE EMPLOYEE(EmpId integer,EmpName VARCHAR(100),EmpSalary integer, DeptId integer);

INSERT INTO EMPLOYEE(EmpId,EmpName,EmpSalary,DeptId)
VALUES(1,'ANAND',70000,1),
(2,'KALPANA',10000,2),
(3,'SUBHASIS',23000,2),
(4,'MAMA',3400,1),
(5,'SUVAM',8700,3),
(6,'SWAYAM',6700,1),
(7,'SWAGAT',8346,3),
(8,'AYUSH',7600,3),
(9,'SUBHENDU',3000,1),
(10,'PANIGRAHI',7000,2);
 
SELECT * FROM EMPLOYEE;
 
CREATE TABLE DEPT(DeptId integer,DeptName VARCHAR(100));

INSERT INTO DEPT(DeptId,DeptName)
VALUES(1,'MICROSOFT'),
(2,'SAP'),
(3,'SALESFORCE'),
(4,'DA');

--INNER JOIN
SELECT EMPLOYEE.EmpId, EMPLOYEE.EmpName, DEPT.DeptName 
FROM Employee 
INNER JOIN DEPT
ON Employee.DeptId = DEPT.DeptId;

--LEFT JOIN
SELECT EMPLOYEE.EmpId, EMPLOYEE.EmpName, DEPT.DeptName 
FROM Employee 
LEFT JOIN DEPT
ON Employee.DeptId = DEPT.DeptId;


--RIGTH JOIN
SELECT EMPLOYEE.EmpId, EMPLOYEE.EmpName, DEPT.DeptName 
FROM Employee 
RIGHT JOIN DEPT
ON Employee.DeptId = DEPT.DeptId;


--FULL OUTER JOIN
SELECT EMPLOYEE.EmpId, EMPLOYEE.EmpName, DEPT.DeptName 
FROM Employee 
FULL OUTER JOIN DEPT
ON Employee.DeptId = DEPT.DeptId;