SELECT * FROM CUST;
SELECT * FROM CUSTOMER_DETAILS;

--LEFT JOIN
SELECT CUST.ADDRESS, CUSTOMER_DETAILS.CUSTOMER_NAME
FROM CUST
LEFT JOIN CUSTOMER_DETAILS
ON CUST.CUSTOMER_ID = CUSTOMER_DETAILS.CUSTOMER_ID;

--RIGHT JOIN

SELECT CUST.CUSTOMER_ID, CUSTOMER_DETAILS.DUE_AMOUNT
FROM CUST
RIGHT JOIN CUSTOMER_DETAILS
ON CUST.CUSTOMER_ID = CUSTOMER_DETAILS.CUSTOMER_ID;

--FULL JOIN
SELECT CUST.PIN_CODE, CUSTOMER_DETAILS.CUSTOMER_NAME
FROM CUST
FULL OUTER JOIN CUSTOMER_DETAILS
ON CUST.CUSTOMER_ID = CUSTOMER_DETAILS.CUSTOMER_ID;

--BETWEEN OPERATOR
SELECT CUSTOMER_NAME, CONTACT_NUMBER
FROM CUSTOMER_DETAILS
WHERE DUE_AMOUNT BETWEEN 1000 AND 10000;

--IN OPERATOR
SELECT CUSTOMER_NAME, CUSTOMER_ID
FROM CUSTOMER_DETAILS
WHERE ORDER_AMOUNT IN (1,2,4,6,8,9,10,5);

--LIKE OPERATOR
SELECT CUSTOMER_ID
FROM CUSTOMER_DETAILS 
WHERE CUSTOMER_NAME LIKE '%AM';

-- Create Customer table
CREATE TABLE Customer (
    CustomerID INT PRIMARY KEY,
    Name VARCHAR(100),
    Email VARCHAR(100),
    Phone VARCHAR(20),
    Address VARCHAR(255)
);

CUSTOMER_XYZ,CUSTOMER_NEW

CREATE TABLE  CUSTOMER_A(CustomerID INT, Name VARCHAR(20), Email VARCHAR(50), Phone INT, Address VARCHAR(50));


INSERT INTO CUSTOMER_A VALUES (2, 'Jane', 'jane.smith@example.com', '1987654321', '456 Elm Street, City'),(3, 'Alice', 'alice.johnson@example.com', '1122334455', '789 Oak Avenue, City');    

  
SELECT * FROM CUSTOMER_LIST;


--INTERSECT OPERATOR
SELECT * FROM CUSTOMER_LIST
INTERSECT
SELECT * fROM CUSTOMER_A;

--MINUS OPERATOR
SELECT * FROM CUSTOMER_LIST
MINUS
SELECT * fROM CUSTOMER_A;