/*CREATE DATABASE FIRSTDB;1. DATABASE CREATED*/
CREATE TABLE CUSTOMER_DETAILS
(
	CUSTOMER_ID INT NOT NULL,
	CUSTOMER_NAME VARCHAR(20),
	CONTACT_NUMBER INT NOT NULL,
	DUE_AMOUNT INT,
	ORDER_AMOUNT INT,
	PRIMARY KEY (CUSTOMER_ID)
);
INSERT INTO CUSTOMER_DETAILS
VALUES
(12, 'RAM', 911, 9876, 6),
(13, 'SHAM', 811, 98765, 9),
(14,'RAJ' , 711, 82727, 10),
(15,'ROSHAN' , 111, 8227, 5),
(19,'RAHUL' , 411, 2727, 4);

SELECT * FROM CUSTOMER_DETAILS;

CREATE TABLE CUST
(
	ADDRESS VARCHAR(30),
	PIN_CODE INT NOT NULL,
	CUSTOMER_ID INT,
	FOREIGN KEY (CUSTOMER_ID)
	REFERENCES CUSTOMER_DETAILS(CUSTOMER_ID)
);
INSERT INTO CUST
VALUES
('BANGALORE', 123456, 19),
('MUMBAI', 567890, 15),
('BHUBANESWAR', 467889, 13);
SELECT * FROM CUST;

SELECT CUSTOMER_DETAILS.DUE_AMOUNT, CUST.ADDRESS, CUSTOMER_DETAILS.CUSTOMER_ID
FROM CUSTOMER_DETAILS
INNER JOIN CUST ON
CUST.CUSTOMER_ID = CUSTOMER_DETAILS.CUSTOMER_ID;
ALTER TABLE CUST
ADD MODEL_NAME VARCHAR(20);


WITH CTE1 AS (SELECT PIN_CODE, CUSTOMER_ID FROM CUST)
SELECT * FROM CTE1;
